---
- name: Ensure mysql python bindings are installed (Ansible requirement)
  ansible.builtin.apt:
    name: python3-mysqldb
    state: present

- name: Ensure mysql server is installed
  ansible.builtin.apt:
    name: mysql-server
    state: present

- name: Restart MySQL
  ansible.builtin.service:
    name: mysql
    state: restarted

- name: Ensure MySQL service is started and set to start on boot
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Update mysql root password
  community.mysql.mysql_user:
    user: "root"
    password: "{{ mysql_root_password }}"
    host: "localhost"
    login_user: "root"
    login_password: ""
